spring:
  application:
    name: alarm-service
  config:
    import: "optional:configserver:"   # 추가가 핵심
  cloud:
    config:
      uri: http://localhost:8888       # config server 주소


# (선택) Eureka on/off 토글(로컬에서 굳이 등록 안 하고 싶을 때)
eureka:
  client:
    enabled: true   # false로 두면 아예 클라이언트 빈 생성 안 함
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true