apiVersion: v1
kind: Service
metadata:
  name: member-service
  labels:
    app: member-service
spec:
  type: ClusterIP
  selector:
    app: member-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081