apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deployment
  labels:
    app: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: 65553a5d-kr1-registry.container.nhncloud.com/cobee-server/config-service:latest
          ports:
            - containerPort: 8888
          envFrom:
            - secretRef:
                name: cobee-secret
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761/eureka/
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
            requests:
              memory: "256Mi"
              cpu: "100m"
      imagePullSecrets:
        - name: registry-credential