spring:
  application:
    name: recruit-service
  config:
    import: "optional:configserver:http://localhost:8888"

# 헬스/인포만 열기
management:
  endpoints:
    web:
      exposure:
        include: health,info

# Eureka on/off 토글(로컬에서 굳이 등록 안 하고 싶을 때)
eureka:
  client:
    enabled: true   # false : 아예 클라이언트 빈 생성 X