server:
  port: 8083

spring:
  application:
    name: chat-service
  config:
    import: "optional:configserver:"   # 추가가 핵심
  cloud:
    config:
      uri: http://localhost:8888       # config server 주소

  datasource:
    url: ${POSTGRES_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  data:
    mongodb:
      uri: ${MONGODB_URI}

app:
  backend:
    url: ${BACKEND_URL:http://localhost:8080}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true