spring:
  application:
    name: chat-service
  config:
    import: "optional:configserver:"   # 추가가 핵심
  cloud:
    config:
      uri: http://localhost:8888       # config server 주소


# (선택) 헬스/인포만 열기
management:
  endpoints:
    web:
      exposure:
        include: health,info


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true