apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  labels:
    app: apigateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway-service
  template:
    metadata:
      labels:
        app: apigateway-service
    spec:
      containers:
        - name: apigateway-service
          image: 65553a5d-kr1-registry.container.nhncloud.com/cobee-server/apigateway-service:latest
          ports:
            - containerPort: 8080
          # 환경 변수를 통해 Eureka 및 Config Server 설정
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761/eureka/
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8888
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"