server:
  port: 8080

spring:
  application:
    name: apigateway-service
  config:
    import: "optional:configserver:"     # ★ Config Server에서 외부설정 당겨오기
  cloud:
    config:
      uri: http://localhost:8888         # ★ Config Server 주소
    gateway:
      server:
        webflux:
          routes:
            - id: member-oauth
              uri: lb://MEMBER-SERVICE
              predicates:
                - Path=/oauth2/**
            - id: member-login
              uri: lb://MEMBER-SERVICE
              predicates:
                - Path=/login/**
            - id: member-refresh
              uri: lb://MEMBER-SERVICE
              predicates:
                - Path=/auth/refresh
            - id: member-auth
              uri: lb://MEMBER-SERVICE
              predicates:
                - Path=/auth/**
              filters:
                - AuthorizationHeaderFilter
            - id: member-ocr
              uri: lb://MEMBER-SERVICE
              predicates:
                - Path=/ocr/**
                - Method=POST
              filters:
                - AuthorizationHeaderFilter
            - id: recruit
              uri: lb://RECRUIT-SERVICE
              predicates: Path=/recruit/**
              filters:
                - AuthorizationHeaderFilter
            - id: alarm
              uri: lb://ALARM-SERVICE
              predicates: Path=/alarm/**
#              filters:
#                - AuthorizationHeaderFilter
            - id: apply
              uri: lb://RECRUIT-SERVICE
              predicates: Path=/apply/**
              filters:
                - AuthorizationHeaderFilter
            - id: member
              uri: lb://MEMBER-SERVICE
              predicates: Path=/members/**
              filters:
                - AuthorizationHeaderFilter
            - id: comment
              uri: lb://RECRUIT-SERVICE
              predicates: Path=/comments/**
              filters:
                - AuthorizationHeaderFilter
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expire-time: 86400000
  refresh-token-expire-time: 604800000

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG